# k8s/artifactory-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifactory
  namespace: jfrog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artifactory
  template:
    metadata:
      labels:
        app: artifactory
    spec:
      containers:
      - name: artifactory
        image: docker.io/jfrog/artifactory-oss:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: artifactory-data
          mountPath: /var/opt/jfrog/artifactory
      volumes:
      - name: artifactory-data
        emptyDir: {}  # For demo/testing only, no data persistence
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  namespace: jfrog
spec:
  type: NodePort
  selector:
    app: artifactory
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
